version: '3.8'
services:
  app:
    container_name: blog_app
    build: ./
    ports:
      - "22309:3000"
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
  mysql:
    container_name: blog_mysql
    build: ./dockerfiles/mysql
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init-db.sql
volumes:
    mysql-data:
        driver: "local"